menu_position.menu_position.*:
  type: config_entity
  label: 'Menu position config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    enabled:
      type: boolean
      label: 'Whether the rule is enabled or not'
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Condition'
    menu_name:
      type: string
      label: 'The menu of the menu link for this rule'
    plid:
      type: string
      label: 'The parent menu link id for this rule'
    mlid:
      type: string
      label: 'The menu link id for this rule'
    weight:
      type: integer
      label: 'The weight of this rule'
    machine_name:
      type: string
      label: 'The machine name'
